name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
    inputs:
      tags:
        type: choice
        description: 'Enter the tags to run the tests'
        required: true
        default: '@login'
        options:
          - @login
          - @regression
          - @smoke

#env:
#    MAVEN_OPTS: "-Xmx2g -XX:MaxPermSize=512m"

jobs:
  Paywright-Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Print Variables
        #run: echo "${{vars.PLAYWRIGHT}} This will print in console using maven opts variable"
        run: echo ${{ inputs.tags }}


#      - name: Install dependencies
#        run: npm ci

#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
#
#      - name: Run Playwright tests
#        run: mvn clean test -Dcucumber.filter.tags=@login


#      - name: Upload Report Artifact
#        uses: actions/upload-artifact@v4
#        if: ${{ !cancelled() }}
#        with:
#          name: cucumber-report
#          path: target/
#          retention-days: 30
